---
title: "My 'trees' Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
    theme: sandstone
    logo: "../img/tree-logo-resized.png"
    favicon: "../img/tree-logo-resized.png"

---



```{r setup, include=FALSE}
library(flexdashboard)

# Tables
library(DT)

# Plotting
library(ggplot2)
library(plotly)

# Analysis
library(corrr)

# Other
library(emo)

```


Page 1
================================

Row {data-height=600}
-----------------------------------------------------------------------

### Super Informative Scatterplot

```{r}
plot_tree <- ggplot(trees, aes(Girth, Height)) +
  geom_point(aes(colour = Volume), size = 4) +
  #scale_color_gradient(low="blue", high="red") +
  scale_color_gradientn(colours = rainbow(5)) +
  theme_bw()
  
ggplotly(plot_tree)

```

Row {data-height=400}
-----------------------------------------------------------------------

### Correlation Matrix

```{r}
trees_cor <- trees %>% 
  correlate() 

trees_cor %>% 
  rearrange() %>% 
  fashion() %>% 
  knitr::kable()

```

### Chart `r ji("grinning")`

*Put something interesting here.*  
`r ji("bar_chart")`  
```{r}
hist(trees$Volume)

```

Page 2
================================

Column
-----------------------------------------------------------------------

### Data Explorer

```{r}
datatable(trees,
          style = "bootstrap4",
          caption = "Diameter, Height and Volume for Black Cherry Trees",
          # options = list(
          #   scrollY = '450px'
          # )
)


```







