---
title: "Hotel Bookings"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    theme: lumen
    source_code: embed

---



```{r setup, include = FALSE}
library(flexdashboard)
library(readr)       # for importing data
library(vip)         # for variable importance plots

```



```{r data}
# Import data
hotels <- 
  read_csv('https://tidymodels.org/start/case-study/hotels.csv') %>%
  mutate_if(is.character, as.factor) 

```


```{r splitting}
# Data splitting and resampling
set.seed(123)
splits <- initial_split(hotels, strata = children)

hotel_other <- training(splits)
hotel_test  <- testing(splits)


# Create a validation set
set.seed(234)
val_set <- validation_split(hotel_other, 
                            strata = children, 
                            prop   = 0.80)

```


```{r lasso}
# Model
lr_mod <- 
  logistic_reg(mixture = 1, penalty = tune()) %>% 
  set_engine("glmnet")


# Recipe
holidays <- c("AllSouls", "AshWednesday", "ChristmasEve", "Easter", 
              "ChristmasDay", "GoodFriday", "NewYearsDay", "PalmSunday")

lr_recipe <- 
  recipe(children ~ ., data = hotel_other) %>%   #remember that `hotel_other` is just a template here
  step_date(arrival_date) %>% 
  step_holiday(arrival_date, holidays = holidays) %>% 
  step_rm(arrival_date) %>% 
  step_dummy(all_nominal(), -all_outcomes()) %>% 
  step_zv(all_predictors()) %>% 
  step_normalize(all_predictors())


# Workflow
lr_workflow <- 
  workflow() %>% 
  add_model(lr_mod) %>% 
  add_recipe(lr_recipe)


# Tuning
lr_reg_grid <- tibble(penalty = 10^seq(-4, -1, length.out = 10)) #length.out = 30

lr_res <- 
  lr_workflow %>% 
  tune_grid(val_set,
            grid    = lr_reg_grid,
            control = control_grid(save_pred = TRUE),
            metrics = metric_set(roc_auc))

```


```{r results}
lr_plot <- 
  lr_res %>% 
  collect_metrics() %>% 
  ggplot(aes(x = penalty, y = mean)) + 
  geom_point() + 
  geom_line() + 
  ylab("Area under the ROC Curve") +
  scale_x_log10(labels = scales::label_number())

lr_plot 


top_models <-
  lr_res %>% 
  show_best("roc_auc", n = 20) %>% 
  arrange(penalty) 
top_models


lr_res %>% 
  select_best("roc_auc")


# We may want to choose a penalty value further along the x-axis, 
# closer to where we start to see the decline in model performance. 
# For example, candidate model 12 with a penalty value of 0.00137 
# has effectively the same performance as the numerically best model,
# but might eliminate more predictors.
top_models %>% 
  slice(12)

lr_plot + 
  geom_vline(xintercept = 0.000530,
                 color      = 'red',
                 linetype   = 'dotted') +
  geom_vline(xintercept = 0.00137,
             color      = 'red')



lr_best <- 
  lr_res %>% 
  collect_metrics() %>% 
  arrange(penalty) %>% 
  slice(12)
lr_best


lr_auc <- 
  lr_res %>% 
  collect_predictions(parameters = lr_best) %>% 
  roc_curve(children, .pred_children) %>% 
  mutate(model = "Logistic Regression")

autoplot(lr_auc)


### need to predict first
lr_res %>% 
  collect_predictions(parameters = lr_best) %>% 
  conf_mat(truth = children, estimate = .pred_children, dnn = c("Prediction", "Truth"))
  
autoplot.conf_mat(object, type = "mosaic", ...)



```








Column {.sidebar}
-----------------------------------------------------------------------








## Column {data-width="650"}

### Chart A

```{r}

```

## Column {data-width="350"}

### Chart B

```{r}

```

### Chart C

```{r}

```
