---
title: "Exploring MPG"
output: 
  flexdashboard::flex_dashboard:
    theme:
      bg: "#101010"
      fg: "#FDF7F7" 
      primary: "#ED79F9"
      base_font:
        google: Prompt
      code_font:
        google: JetBrains Mono
    orientation: columns
    vertical_layout: fill
runtime: shiny
    
---

```{r setup, include=FALSE}
library(tidyverse)
library(flexdashboard)
library(ggplot2)
library(thematic)
library(shiny)
# Install thematic and un-comment for themed static plots (i.e., ggplot2)
# thematic::thematic_rmd()
```



Sidebar {.sidebar}
===========================================================


```{r}

choice <- mtcars %>% select(-mpg) %>% select(where(is.numeric)) %>% names()

selectInput(
  inputId = "select_var",
  label   = "Select Predictor",
  choices = choice,
  selected = "wt"
  )

# thematic_rmd()

# renderPrint(input$select_var)

```




Tab1 {data-width=650 .tabset}
==================================

### Chart A

```{r}

# plot(mtcars$wt, mtcars$mpg)


output$p <- renderPlot({ggplot(mtcars, aes_string(x = input$select_var, y = "mpg")) +
  geom_point() + # Add points
  labs(
    title = paste0("Scatter plot of ", input$select_var, " vs mpg"),
    x = input$select_var,
    y = "Miles per Gallon"
  )
})

plotOutput(outputId = "p")


```

### Chart B

```{r}
skimr::skim(mtcars)

```

Tab2 {data-width=350}
============================

### Chart C

```{r}

```

### Chart D

```{r}

```

